log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: vless
  settings:
    clients:
    - id: "b1bb823b-1bc8-4859-b711-261d147c6db1"
    decryption: "none"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
